name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.gcp_credentials }}

      - name: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: us.gcr.io/bensnyde-me/website
          service: static-website
          region: us-central1
          project_id: bensnyde-me
