name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.gcp_credentials }}

      - name: configure docker
        run: gcloud auth configure-docker us.gcr.io --quiet

      - name: build and push image
        run: |
          docker build -t us.gcr.io/bensnyde-me/website:${{ github.sha }} .
          docker push us.gcr.io/bensnyde-me/website:${{ github.sha }}

      - name: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: us.gcr.io/bensnyde-me/website:${{ github.sha }}
          service: static-website
          region: us-central1
          project_id: bensnyde-me
